from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
import base64

import pandas as pd
import markdown
import matplotlib.pyplot as plt
from weasyprint import HTML


# -----------------------
# HTML TEMPLATE
# -----------------------

HTML_TEMPLATE = """
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>VisaOps Risk Report</title>
<style>
body {{
  font-family: Arial, sans-serif;
  margin: 36px;
  line-height: 1.5;
  color: #111;
}}
h1, h2, h3 {{
  color: #1f4e79;
}}
table {{
  border-collapse: collapse;
  width: 100%;
  margin: 14px 0;
}}
th, td {{
  border: 1px solid #d0d7de;
  padding: 8px;
  font-size: 0.95em;
}}
th {{
  background: #f6f8fa;
}}
.figure-block {{
  margin-top: 18px;
  padding: 10px;
  border: 1px solid #d0d7de;
  border-radius: 6px;
}}
.figure-title {{
  font-weight: 600;
  margin-bottom: 6px;
}}
img {{
  max-width: 100%;
}}
hr {{
  margin: 18px 0;
}}
.footnote {{
  font-size: 0.9em;
  color: #555;
}}
</style>
</head>
<body>

{content}

<h2>Last 7 Days — Key Operational Drivers</h2>

<table>
<tr>
<th>Metric</th>
<th>Last 7d Avg</th>
<th>Prev 7d Avg</th>
<th>Δ</th>
</tr>
{driver_rows}
</table>

<p><strong>Interpretation:</strong> {driver_summary}</p>

<div class="figure-block">
  <div class="figure-title">Stress Index & Regime Timeline ({center})</div>
  <img src="data:image/png;base64,{figure_b64}">
</div>

<hr>
<div class="footnote">
Generated by VisaOps Risk Console (demo). Data is synthetic and non-sensitive.
</div>

</body>
</html>
"""


# -----------------------
# HELPERS
# -----------------------

def find_latest_memo() -> Path:
    memos = sorted(
        Path("reports").glob("memo_*.md"),
        key=lambda p: p.stat().st_mtime,
        reverse=True
    )
    if not memos:
        raise FileNotFoundError("No memo_*.md found in reports/")
    return memos[0]


def infer_center(md_path: Path) -> str:
    return md_path.stem.replace("memo_", "")


def load_signals() -> pd.DataFrame:
    path = Path("data/processed/visaops_signals.csv")
    if not path.exists():
        raise FileNotFoundError("visaops_signals.csv missing")
    df = pd.read_csv(path)
    df["date"] = pd.to_datetime(df["date"])
    return df


# -----------------------
# DRIVER COMPUTATION
# -----------------------

def compute_7d_drivers(df: pd.DataFrame, center: str) -> tuple[list[str], str]:
    d = df[df["center"] == center].sort_values("date").copy()

    last_14 = d.tail(14)
    last_7 = last_14.tail(7)
    prev_7 = last_14.head(7)

    metrics = {
        "Avg TAT (days)": "avg_tat_days",
        "Queue velocity": "queue_delta",
        "Utilization": "utilization",
    }

    rows = []
    deltas = {}

    for label, col in metrics.items():
        cur = last_7[col].mean()
        prev = prev_7[col].mean()
        delta = cur - prev
        deltas[label] = delta

        rows.append(
            f"<tr><td>{label}</td>"
            f"<td>{cur:.2f}</td>"
            f"<td>{prev:.2f}</td>"
            f"<td>{delta:+.2f}</td></tr>"
        )

    # Simple rule-based explanation
    if deltas["Queue velocity"] > 0 and deltas["Avg TAT (days)"] > 0:
        summary = "Rising stress driven primarily by increasing queue accumulation and turnaround time."
    elif deltas["Utilization"] > 0.05:
        summary = "Operational pressure driven by rising utilization over the past week."
    elif deltas["Queue velocity"] < 0:
        summary = "Stress easing due to declining queue accumulation."
    else:
        summary = "No dominant operational driver detected over the last 7 days."

    return rows, summary


# -----------------------
# PLOT
# -----------------------

def make_plot(df: pd.DataFrame, center: str, out_png: Path):
    d = df[df["center"] == center].sort_values("date")

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.plot(d["date"], d["stress_index"], linewidth=2)
    ax.axhline(0, linestyle="--", linewidth=1)

    colors = {
        "stable": "#d4f4dd",
        "elevated": "#fff3cd",
        "stressed": "#f8d7da"
    }

    ymin, ymax = d["stress_index"].min(), d["stress_index"].max()
    for r, c in colors.items():
        ax.fill_between(
            d["date"],
            ymin,
            ymax,
            where=(d["regime"] == r),
            alpha=0.35,
            color=c
        )

    ax.set_title(f"Stress Index — {center}")
    ax.tick_params(axis="x", rotation=30)
    fig.tight_layout()

    out_png.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_png, dpi=180)
    plt.close(fig)


def png_to_b64(p: Path) -> str:
    return base64.b64encode(p.read_bytes()).decode()


# -----------------------
# MAIN
# -----------------------

def main():
    reports = Path("reports")
    reports.mkdir(exist_ok=True)

    memo = find_latest_memo()
    center = infer_center(memo)

    df = load_signals()

    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M")
    png = reports / f"stress_regime_{center}_{ts}.png"
    pdf = reports / f"visaops_report_{ts}.pdf"

    make_plot(df, center, png)
    driver_rows, driver_summary = compute_7d_drivers(df, center)

    html_body = markdown.markdown(memo.read_text(), extensions=["tables"])
    html = HTML_TEMPLATE.format(
        content=html_body,
        center=center,
        driver_rows="\n".join(driver_rows),
        driver_summary=driver_summary,
        figure_b64=png_to_b64(png),
    )

    HTML(string=html).write_pdf(str(pdf))
    print(f"PDF generated -> {pdf}")


if __name__ == "__main__":
    main()
