from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
import base64

import markdown
import pandas as pd
import matplotlib.pyplot as plt
from weasyprint import HTML


HTML_TEMPLATE = """
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>VisaOps Risk Report</title>
  <style>
    body {{
      font-family: Arial, sans-serif;
      margin: 38px;
      line-height: 1.5;
      color: #111;
    }}
    h1, h2, h3 {{
      color: #1f4e79;
      margin-bottom: 8px;
    }}
    h1 {{ margin-top: 0; }}
    p {{ margin: 8px 0; }}
    ul {{ margin: 6px 0 12px 22px; }}
    code {{
      background: #f6f8fa;
      padding: 2px 4px;
      border-radius: 4px;
      font-size: 0.95em;
    }}
    table {{
      border-collapse: collapse;
      width: 100%;
      margin: 14px 0;
      font-size: 0.95em;
    }}
    th, td {{
      border: 1px solid #d0d7de;
      padding: 8px;
      text-align: left;
      vertical-align: top;
    }}
    th {{
      background-color: #f6f8fa;
      font-weight: 600;
    }}
    hr {{
      border: none;
      border-top: 1px solid #d0d7de;
      margin: 18px 0;
    }}
    .figure-block {{
      margin: 14px 0 18px 0;
      padding: 10px 12px;
      border: 1px solid #d0d7de;
      border-radius: 8px;
      background: #fbfcfe;
    }}
    .figure-title {{
      font-weight: 600;
      margin-bottom: 8px;
      color: #1f4e79;
    }}
    .figure-caption {{
      margin-top: 8px;
      font-size: 0.9em;
      color: #444;
    }}
    img {{
      max-width: 100%;
      height: auto;
      display: block;
    }}
    .footnote {{
      margin-top: 18px;
      font-size: 0.9em;
      color: #555;
    }}
    @page {{
      size: A4;
      margin: 18mm 16mm 18mm 16mm;
    }}
  </style>
</head>
<body>

{content}

<div class="figure-block">
  <div class="figure-title">Figure — Stress Index with Regime Shading ({center})</div>
  <img src="data:image/png;base64,{figure_b64}" alt="Stress index regime plot">
  <div class="figure-caption">
    Regimes are rule-based labels on the composite stress index (stable / elevated / stressed).
  </div>
</div>

<hr/>
<div class="footnote">
  Generated by VisaOps Risk Console (demo). Data is synthetic and non-sensitive.
</div>

</body>
</html>
"""


def find_latest_memo() -> Path:
    candidates = sorted(
        Path("reports").rglob("memo_*.md"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if not candidates:
        raise FileNotFoundError(
            "No memo_*.md found under reports/.\n"
            "Fix: Export a memo from Streamlit and save it into reports/."
        )
    return candidates[0]


def infer_center_from_memo(md_path: Path) -> str:
    stem = md_path.stem  # e.g. memo_Bengaluru
    if stem.lower().startswith("memo_") and len(stem) > 5:
        return stem.split("memo_", 1)[1]
    return "Unknown"


def load_signals() -> pd.DataFrame:
    path = Path("data/processed/visaops_signals.csv")
    if not path.exists():
        raise FileNotFoundError("Missing data/processed/visaops_signals.csv. Run your pipeline to generate signals.")
    df = pd.read_csv(path)
    df["date"] = pd.to_datetime(df["date"])
    return df


def make_regime_plot(df: pd.DataFrame, center: str, out_png: Path) -> None:
    d = df[df["center"] == center].sort_values("date").copy()
    if d.empty:
        raise ValueError(f"No rows found for center='{center}' in visaops_signals.csv")

    for col in ["stress_index", "regime"]:
        if col not in d.columns:
            raise ValueError(f"Missing required column '{col}' in visaops_signals.csv")

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.plot(d["date"], d["stress_index"], linewidth=2)
    ax.axhline(0, linestyle="--", linewidth=1)

    regime_colors = {"stable": "#d4f4dd", "elevated": "#fff3cd", "stressed": "#f8d7da"}
    ymin = float(d["stress_index"].min())
    ymax = float(d["stress_index"].max())
    if ymin == ymax:
        ymin -= 1.0
        ymax += 1.0

    reg_series = d["regime"].astype(str).str.lower()
    for reg, col in regime_colors.items():
        mask = (reg_series == reg).to_numpy()
        ax.fill_between(d["date"], ymin, ymax, where=mask, color=col, alpha=0.35)

    ax.set_title(f"Operational Stress & Regimes — {center}")
    ax.set_xlabel("Date")
    ax.set_ylabel("Stress Index")
    ax.tick_params(axis="x", rotation=30)
    fig.tight_layout()

    out_png.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_png, dpi=180, facecolor="white")
    plt.close(fig)


def png_to_base64(png_path: Path) -> str:
    data = png_path.read_bytes()
    return base64.b64encode(data).decode("utf-8")


def main() -> None:
    reports_dir = Path("reports")
    reports_dir.mkdir(parents=True, exist_ok=True)

    md_file = find_latest_memo()
    center = infer_center_from_memo(md_file)

    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M")
    out_pdf = reports_dir / f"visaops_report_{ts}.pdf"
    out_png = reports_dir / f"stress_regime_{center}_{ts}.png"

    df = load_signals()
    make_regime_plot(df, center=center, out_png=out_png)
    print(f"Figure saved -> {out_png}")

    md_text = md_file.read_text(encoding="utf-8")
    html_body = markdown.markdown(md_text, extensions=["tables"])
    fig_b64 = png_to_base64(out_png)

    html = HTML_TEMPLATE.format(content=html_body, center=center, figure_b64=fig_b64)

    # Render PDF from HTML string (no external image paths involved)
    HTML(string=html).write_pdf(str(out_pdf))
    print(f"PDF report generated -> {out_pdf}")


if __name__ == "__main__":
    main()
